---
antora:
  name: modules
  dir: www
  modules:
    - name: "01-introduction"
      label: "Introduction"
      solveButton: true
    - name: "02-installnmstate"
      label: "Installnmstate"
      solveButton: true
    - name: "03-dhcpconfig"
      label: "Dhcpconfig"
      solveButton: true
    - name: "04-staticconfig"
      label: "Staticconfig"
      solveButton: true
    - name: "05-activateconnection"
      label: "Activateconnection"
      solveButton: true
    - name: "06-configdns"
      label: "Configdns"
      solveButton: true

tabs:
  - name: ">_ terminal"
    url: /wetty
