---
antora:
  name: modules
  dir: www
  modules:
    - name: "01-introduction"
      label: "Introduction"
    - name: "02-installnmstate"
      label: "Installnmstate"
    - name: "03-dhcpconfig"
      label: "Dhcpconfig"
    - name: "04-staticconfig"
      label: "Staticconfig"
    - name: "05-activateconnection"
      label: "Activateconnection"
    - name: "06-configdns"
      label: "Configdns"

tabs:
  - name: ">_ terminal"
    url: /wetty_host1/ssh/root
